### ISSUE TITLE
--since 4.1.0, was the tag treated as a date?

### ISSUE THREAD

**Issue by consideRatio** [executablebooks/github-activity#15]
I'm not sure what went wrong, but I passed --since 4.1.0 and it was like it didn't consider it a git reference. When I instead passed refs/tags/4.1.0 everything worked as I expected. So perhaps 4.1.0 was treated as a date?

```
# these are very different
github-activity jupyterhub/configurable-http-proxy --kind pr --since 4.1.0
github-activity jupyterhub/configurable-http-proxy --kind pr --since refs/tags/4.1.0
```

**Comment by choldgraf** [comment]
Ah, I bet this is the case!
