### ISSUE TITLE
Feature: finding and using a default target repo when used from a local git repo

### ISSUE THREAD

**Issue by consideRatio** [executablebooks/github-activity#21]
My main use of this tool is from a terminal while working on a git repo, as I want to update the git repos changelog file. For me, it would be a convenience to not have to specify the target to be jupyterhub/chartpress when working there for example. But at the same time, its fine as well.

One may end up probing an un-updated fork, so perhaps we should just close this feature request due to not having a reliable method to implement a default assumption of what repo to work with. Hmmm... I figured I'd write it to process it. I'm happy to close it quickly again because it isn't worth the effort to implement the solution that would be reliable enough to motivate implementation.

**Comment by choldgraf** [comment]
could one make the following assumption:

1. Check if we are currently in a git repository. If yes, then:
2. Check if there is a remote called "upstream" defined. If so, assume that the github org/repo of upstream is what one wants by default.
3. If not, check if there is a remote called "origin" defined. If so, do the same thing.
4. If neither of these are the case, the user needs to manually provide the info

**Comment by choldgraf** [comment]
@consideRatio I wonder if the recent dependence on the `git` package would let us easily solve this one? After using this package a bit more, 99% of the time I am running it for the repository I am already in, and this would save a lot of typing :-)
