### ISSUE TITLE
CI: run pytest with bot accounts access token

### ISSUE THREAD

**Issue by consideRatio** [executablebooks/github-activity#28]
Is it correct that we don't run `pytest` in the CI system atm? I figure it could be a bit problematic with regards to needing a GITHUB_ACCESS_TOKEN, but perhaps we could provide one for a bot account, and provide it as a GitHub secret.

Here is some details about secrets for GitHub actions: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by choldgraf** [comment]
I'm +1 on that! It's not too hard to set up, see my jupyter-activity-snapshot repo for a gh actions configuration that uses this

**Comment by blink1073** [comment]
Fixed by https://github.com/executablebooks/github-activity/pull/45
