### ISSUE TITLE
Switch from GraphQL to use ghapi instead

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/github-activity#48]
The [ghapi tool](https://ghapi.fast.ai/) is a lightweight Python wrapper around the GitHub API. It is programmatically generated, so it is always up-to-date with the latest GitHub API changes.

**here's a PR to prototype this: https://github.com/executablebooks/github-activity/pull/49/files**

It is much more pythonic and intuitive than figuring out the right GraphQL incantations, especially when you're not so concerned about too many API calls. For example, I think that we could basically clobber our entire GraphQL call here:

https://github.com/executablebooks/github-activity/blob/master/github_activity/graphql.py#L9

with a couple of calls to `api.search.issues_and_pull_requests`

Cc @hamelsmu who shared this with me!

# Things to do

- [ ] Re-write the GraphQL queries to use `ghapi` instead and see how they compare
- [ ] Things to fix
  - [ ] With GraphQL queries, we are requesting extra information than the GitHub API v3 will give. This includes: (for pull requests) the merge commit and the mergecommit author, and (for both PRs and issues) the list of comments in that issue.

# How we'd get each type of activity

There are basically three types of activity that we grab in `github-activity`. Overviews for issues/PRs updated in a window of time, comments in issues/PRs, and merge commit information for PRs. We get all of this with a single GraphQL query, but if we use the GH APIv3, we'll need to separate this out into a few different queries.

**Issues/PRs**

- `api.issues.list_for_repo` (https://docs.github.com/en/rest/reference/issues#list-repository-issues)

Here we can use the `since=<date>` keyword to only pull issues from a specific date. We can use `pagination` as well, and thus if someone also provides an `until` keyword, we can stop the pagination once there's a date above that `until` value.

**Issue/PR comments**

- `api.issues.list_comments_for_repo` (https://docs.github.com/rest/reference/issues#list-issue-comments-for-a-repository)

We can use the same `since=<date>` approach here to grab the comments over a given period.

**PR merge information**

For this we'll need to first take the PRs that are *closed* in the `Issues/PRs` list above, and subset the ones that were merged within the time frame given.

Then, for those PRs, run:

- `api.pulls.get` (https://docs.github.com/v3/pulls/#get-a-pull-request)

Which will return merge commit information about the PR. (the main thing we want here is the username associated with the merge commit, so we know who was responsible for merging)

# What about for multiple repositories?

AFAIK if we wanted to run the above workflow for an *organization* rather than a single repository, we'd first have to list all repositories in that organization and then run the above once for each repository. This is because for some reason the org-level API call for issues *only lists the issues that are assigned to you* (https://docs.github.com/en/rest/reference/issues#list-organization-issues-assigned-to-the-authenticated-user)

**Comment by chrisjsewell** [comment]
ah intersting 👍

**Comment by hamelsmu** [comment]
cc: @jph00 (I know he would be excited to see others are using it, too)

**Comment by blink1073** [comment]
Should we close this in light of https://github.com/executablebooks/github-activity/pull/49#issuecomment-945028668?

**Comment by choldgraf** [comment]
Yeah i think that is a good call
