### ISSUE TITLE
Exclude PRs merged but not in releasing branch

### ISSUE THREAD

**Issue by minrk** [executablebooks/github-activity#50]
**Is your feature request related to a problem? Please describe.**

Not all merged PRs are merged into the currently to-be-released branch. It would be useful to include only those that are merged into the current branch.

**Describe the solution you'd like**

Specify a branch I am releasing from (default: current branch or repo default), and only include PRs that have been merged into that branch.

The simplest solution is to look at the `base` branch in the pr metadata. This, however, will not include multi-stage PRs (multiple PRs to a feature branch, which is later merged to main). It's a good start, though.

It is possible from the git graph, though, to determine exactly which PRs are ancestors to the current branch. That might be more work than we want to do, and can always be a second improvement later.

**Additional context**

I'm working on a jupyerhub release, and we currently have a long-running 'rbac' branch with merged PRs that are not being released. I have to manually remove those from the generated changelog.

In the future, though, I'd like all of those to be *included* as changelog items, rather than the one big rbac->main merge at the end.

**Comment by choldgraf** [comment]
I think this is a good idea - agreed that we can go with an 80/20 principle here and focus on the low hanging fruit first!

**Comment by blink1073** [comment]
cf https://github.com/executablebooks/github-activity/pull/42

**Comment by minrk** [comment]
closed by #42
