### ISSUE TITLE
Backfill / bootstrap an initial changelog

### ISSUE THREAD

**Issue by jtpio** [executablebooks/github-activity#57]
**Is your feature request related to a problem? Please describe.**

It would be nice for repos that want to adopt `github-activity` to be able to automatically backfill a changelog file.

**Describe the solution you'd like**

Maybe an `--all` flag could make this convenient, something like this:

```bash
github-activity org/repo --auth <github-token> --since 1970-01-01 --branch main --all
```

**Describe alternatives you've considered**

An alternative could be to write a small wrapper around `github-activity` that would fetch all tags, and call `github-activity` sequentially.

Or do that by hand if it's just a couple of releases to backfill.

**Additional context**

**Comment by choldgraf** [comment]
That's a cool idea - I wonder how many lines of code it'd take to do this...if it weren't that many, perhaps one solution would simply be to document this pattern so that others could follow, since this would presumably be a one-time action per project.

**Comment by jtpio** [comment]
Right it would be a one time action only, so a small snippet would be enough.

For the simple case of having only one release branch, the script could loop through all the tags and then call `github-activity` with `--since` and `--until`.

**Comment by jtpio** [comment]
> For the simple case of having only one release branch, the script could loop through all the tags and then call `github-activity` with `--since` and `--until`.

Just tried this approach with a manually exported list of tags, and getting a rate limit error rather quickly:

```
requests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url
```

**Comment by jtpio** [comment]
> getting a rate limit error

Which is strange since the quota looks good when checking with:

```
$ curl -I -H "Authorization: token <token>" https://api.github.com/repos/executablebooks/github-activity/commits/v0.1.1
...
x-oauth-scopes: public_repo
x-accepted-oauth-scopes:
x-github-media-type: github.v3; format=json
x-ratelimit-limit: 5000
x-ratelimit-remaining: 4967
x-ratelimit-reset: 1624439267
x-ratelimit-used: 33
```

**Comment by jtpio** [comment]
> getting a rate limit error

Ah this is actually related to https://github.com/executablebooks/github-activity/issues/46

**Comment by blink1073** [comment]
Here's a [script](https://gist.github.com/blink1073/a13c65f9920f1e5f848211516b36f428) I wrote to bootstrap a couple repos.   I like @jtip's idea of having an `--all` flag on the CLI, happy to contribute that.
