### ISSUE TITLE
Leverage new automatic release notes functionality in github 

### ISSUE THREAD

**Issue by dhirschfeld** [executablebooks/github-activity#58]
### Description / Summary

GitHub now lets you automatically create release notes from a template:
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#creating-a-template-for-automatically-generated-release-notes

Just opening this issue as an FYI, so feel free to close.

### Value / benefit

Potentially less maintenance burden?

**Comment by dhirschfeld** [comment]
I'm not too sure as I'm not actually familiar with this repo - I just saw it pop up in my feed and was intrigued as I've basically implemented the same thing... and am also wondering if I can simply port to the new built-in functionality.

I guess it depends on whether or not the built-in capability does everything you need, and potentially how easy it is to extend if required. I'm not sure of the answers as I haven't looked into it much as yet, but I'll be interested in any discussion about the pros & cons here! 👀

**Comment by blink1073** [comment]
This repo has the nice feature of grouping your changes by category, can be used to bootstrap a changelog that did not have previous entries (pending #57), and in general gives us more flexibility.  It has been extremely useful for JupyterLab and other repos using `jupyter-releaser`, which depends on this tool.

**Comment by choldgraf** [comment]
That is very helpful feedback - I don't understand the GitHub release notes thing to know whether it is fully redundant so I'll take your word on it 👍

**Comment by choldgraf** [comment]
I'm going to close this issue as it seems like we still have a lot of good use out of the categorization, grouping, and automation features of this tool, even though GitHub does also have somewhat overlapping functionality with it!
