### ISSUE TITLE
New maintainer: @blink1073 

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/github-activity#63]
I want to welcome @blink1073 as a maintainer on this repository. Thanks Steve for offering to help with things here and there! :-)

**Comment by choldgraf** [comment]
we can close this issue whenever we like, this is just to make sure folks get notified about the update!

**Comment by blink1073** [comment]
Thanks!  If you add `blink1073` to https://pypi.org/project/github-activity I can cut a 0.2 release

**Comment by consideRatio** [comment]
Wieeee!!! ♥️🥰🎉

**Comment by choldgraf** [comment]
@blink1073 you should actually already be able to create a release, by following the workflow described here: https://executablebooks.org/en/latest/contributing.html#the-process-of-creating-a-release

Wanna give that a shot? Either way I'll add you to pypi as well

**Comment by blink1073** [comment]
:tada: https://pypi.org/project/github-activity/0.2.0/

**Comment by choldgraf** [comment]
wohoo! with that action, I'll close this issue :-)

**Comment by consideRatio** [comment]
@blink1073 thank you for helping out in this project!!!! Seeing your maintenance related notifications drop in makes me happy!

:heart: :tada: feel free to ping me if you ever need review help or similar!

**Comment by blink1073** [comment]
Thanks @consideRatio!
