### ISSUE TITLE
Last release commit includes a local stack trace

### ISSUE THREAD

**Issue by jtpio** [executablebooks/github-activity#81]
### Describe the bug

**context**

Looks like the latest release commit includes an error: https://github.com/executablebooks/github-activity/commit/c26f2c495a1beae05e4942e00f8a04ab3b83d99d

```
Traceback (most recent call
```

**expectation**

The message should likely say something like: "Release 0.3.0"

**problem**

Not a big issue for end users , opening this issue for awareness.

### Reproduce the bug

Open the latest commit: https://github.com/executablebooks/github-activity/commit/c26f2c495a1beae05e4942e00f8a04ab3b83d99d

**Comment by jtpio** [comment]
cc @blink1073 for awareness

**Comment by blink1073** [comment]
Thanks for the heads up!  I updated my manual release script to include `python setup.py --version` as a fallback.

**Comment by choldgraf** [comment]
lol nice, I am all for beautiful chaos of OSS showing up in release commit messages 😅

I think we can close this one?
