### ISSUE TITLE
401 error no matter what kinda auth I try to use

### ISSUE THREAD

**Issue by yuvipanda** [executablebooks/github-activity#96]
I've tried both classic and new PATs, as well as `gh auth login`.

`github-activity  -t https://github.com/jupyterhub/oauthenticator --since 16.3.0`

fails with:

```
Using GH access token stored in `GITHUB_ACCESS_TOKEN`.
Running search query:
repo:jupyterhub/oauthenticator


Traceback (most recent call last):
  File "/Users/yuvipanda/.local/share/virtualenvs/oauthenticator/bin/github-activity", line 8, in <module>
    sys.exit(main())
  File "/Users/yuvipanda/.local/share/virtualenvs/oauthenticator/lib/python3.10/site-packages/github_activity/cli.py", line 176, in main
    md = generate_activity_md(
  File "/Users/yuvipanda/.local/share/virtualenvs/oauthenticator/lib/python3.10/site-packages/github_activity/github_activity.py", line 376, in generate_activity_md
    data = get_activity(
  File "/Users/yuvipanda/.local/share/virtualenvs/oauthenticator/lib/python3.10/site-packages/github_activity/github_activity.py", line 164, in get_activity
    qu.request()
  File "/Users/yuvipanda/.local/share/virtualenvs/oauthenticator/lib/python3.10/site-packages/github_activity/graphql.py", line 146, in request
    raise Exception(
Exception: Query failed to run by returning code of 401. {
  search(first: 50, query: "repo:jupyterhub/oauthenticator created:2000-03-16T00:00:00Z..2024-06-11T22:50:04Z", type: ISSUE) {
    issueCount
    pageInfo {
        endCursor
        hasNextPage
    }
    nodes {
      ... on PullRequest {
                state
        id
        title
        url
        createdAt
        updatedAt
        closedAt
        labels(first: 10) {
            edges {
                node {
                    name
                }
            }
        }
        number
        authorAssociation
        author {
          login
        }
        reactions(content: THUMBS_UP) {
          totalCount
        }

        mergedBy {
          login
        }
        mergeCommit {
          oid
        }
        baseRefName
                comments(last: 100) {
          edges {
            node {
              authorAssociation
              createdAt
              updatedAt
              url
              author {
                login
              }
            }
          }
        }

      }
      ... on Issue {
                state
        id
        title
        url
        createdAt
        updatedAt
        closedAt
        labels(first: 10) {
            edges {
                node {
                    name
                }
            }
        }
        number
        authorAssociation
        author {
          login
        }
        reactions(content: THUMBS_UP) {
          totalCount
        }

                comments(last: 100) {
          edges {
            node {
              authorAssociation
              createdAt
              updatedAt
              url
              author {
                login
              }
            }
          }
        }

      }
    }
  }
}

```

**Comment by minrk** [comment]
#97 fixes an encoding problem when github-activity tries to get the token from gh itself, which would look like this if you _didn't_ specify GITHUB_ACCESS_TOKEN, but it looks like you did.

FWIW, I've been using:

```bash
 export GITHUB_ACCESS_TOKEN=$(gh auth token)
github-activity
```

If that doesn't work, does `gh` have a valid token? (check with `gh api /user`).

If the token is valid and you can use it in curl:

```
curl -H "Authorization: Bearer ${GITHUB_ACCESS_TOKEN}" https://api.github.com/user
```

then you might be hitting requests' weird netrc handling. Do you have anything for api.github.com in your .netrc?

**Comment by minrk** [comment]
was auto-closed because of a magic string in #97

**Comment by yuvipanda** [comment]
Unfortunately the issue persists :( I even fully uninstalled `gh` to no avail

**Comment by yuvipanda** [comment]
I installed from main with `pip install --force -U git+https://github.com/executablebooks/github-activity@main`

**Comment by yuvipanda** [comment]
`curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $(gh auth token)" "https://api.github.com/search/issues?q=repo:jupyterhub/jupyter-server-proxy+created:2000-04-02T00:00:00Z..2024-06-12T20:58:22Z"`

works. It's the same search query that `github-activity` is trying to use and failing

**Comment by minrk** [comment]
Do you have a .netrc file, and does it have api.github.com in it?

**Comment by yuvipanda** [comment]
<img width="338" alt="image" src="https://github.com/executablebooks/github-activity/assets/30430/9e4645cd-d6c2-4a86-b30d-ea4b2da55455">

WELL WOULD YOU LOOK AT THAT :)

Good psychic debugging, @minrk!

I think it would be useful for the app to print 'using netrc credentials' or similar maybe, as currently netrc seems to override what's even explicitly passed

**Comment by minrk** [comment]
Not psychic, personal history! I've been flummoxed by this [requests behavior](https://github.com/psf/requests/issues/3929)  a number of times over the years.

Also, I don't think it's easy for us to detect this because the netrc credentals are loaded deep within requests, so I'm not sure we can warn about it very well. It can be disabled, but not without turning off a bunch of [unrelated settings](https://docs.python-requests.org/en/latest/api/#requests.Session.trust_env) like proxy env, etc. Maybe it's best to disable those, since we aren't likely to use them.
